export const ROLES = {
  INTERNAL_ROLES: {
    ADMIN: 'admin',
    GERENTE: 'ceo',
    SOPORTE: 'soporte'
  },

  EXTERNAL_ROLES: {
    ABOGADO: 'legales',
    RECLAMANTE: 'reclamante'
  }
}

export const INTERNAL_ROLES = ROLES.INTERNAL_ROLES
export const EXTERNAL_ROLES = ROLES.EXTERNAL_ROLES

export const ACCESS_CONTROL = {
  // DASHBOARD
  GET_DASHBOARD: Object.values(INTERNAL_ROLES),

  // CLAIMS
  GET_ALL_CLAIMS: [...Object.values(INTERNAL_ROLES), EXTERNAL_ROLES.ABOGADO],
  GET_MY_CLAIMS: [INTERNAL_ROLES.ADMIN, INTERNAL_ROLES.SOPORTE, EXTERNAL_ROLES.RECLAMANTE],
  GET_ALL_ARBITRATIONS: [...Object.values(INTERNAL_ROLES), EXTERNAL_ROLES.ABOGADO], // front purpose
  GET_MY_ARBITRATIONS: [INTERNAL_ROLES.ADMIN, INTERNAL_ROLES.SOPORTE, EXTERNAL_ROLES.RECLAMANTE], // front purpose
  POST_CLAIM: [INTERNAL_ROLES.ADMIN, EXTERNAL_ROLES.RECLAMANTE],
  PUT_CLAIM: [INTERNAL_ROLES.ADMIN, INTERNAL_ROLES.SOPORTE, EXTERNAL_ROLES.RECLAMANTE],
  DELETE_CLAIM: [INTERNAL_ROLES.ADMIN],

  // CHATS
  GET_CHAT_HISTORY: [INTERNAL_ROLES.ADMIN, INTERNAL_ROLES.GERENTE, INTERNAL_ROLES.SOPORTE, EXTERNAL_ROLES.ABOGADO, EXTERNAL_ROLES.RECLAMANTE, INTERNAL_ROLES.GERENTE],
  GET_CHAT: [INTERNAL_ROLES.ADMIN, INTERNAL_ROLES.GERENTE, INTERNAL_ROLES.SOPORTE, EXTERNAL_ROLES.ABOGADO, EXTERNAL_ROLES.RECLAMANTE],
  PUT_IN_CHAT: [INTERNAL_ROLES.ADMIN, INTERNAL_ROLES.GERENTE, INTERNAL_ROLES.SOPORTE, EXTERNAL_ROLES.RECLAMANTE],

  // NOTIFICATIONS
  GET_NOTIFICATIONS: [INTERNAL_ROLES.ADMIN, INTERNAL_ROLES.SOPORTE],

  // LOGS
  GET_LOGS: Object.values(INTERNAL_ROLES),

  // USERS
  GET_ALL_USERS: [INTERNAL_ROLES.ADMIN, INTERNAL_ROLES.GERENTE],
  GET_USER_PROFILE: [INTERNAL_ROLES.ADMIN, INTERNAL_ROLES.SOPORTE],
  POST_USER: [INTERNAL_ROLES.ADMIN],
  PUT_USER: [INTERNAL_ROLES.ADMIN],
  DELETE_USER: [INTERNAL_ROLES.ADMIN]
}
