name: Docker Image CD

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Delete Old docker container
      run: sudo docker rm -f smartmoveback-container || true
    - name: Pull Docker image
      run: sudo docker pull mattdv57/smartmoveback:latest
    - name: Login Dockerhub
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}} 
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Run Docker container
      run: sudo docker run -d -p 3000:3000 -e MONGO_CONNECTION_STRING2="${{ secrets.MONGO_CONNECTION_STRING2 }}" -e PORT="${{ secrets.PORT }}" -e ACCESS_TOKEN_SECRET="${{ secrets.ACCESS_TOKEN_SECRET }}" -e DOCKER_PASSWORD="${{ secrets.DOCKER_PASSWORD }}" -e DOCKER_USER="${{ secrets.DOCKER_USER }}" -e LDAP_ADMIN_DN="${{ secrets.LDAP_ADMIN_DN }}" -e LDAP_ADMIN_PASSWORD="${{ secrets.LDAP_ADMIN_PASSWORD }}" -e LDAP_URL="${{ secrets.LDAP_URL }}" -e DATABASE_URL="${{ secrets.DATABASE_URL }}" -e REFRES_TOKEN_SECRET="${{ secrets.REFRES_TOKEN_SECRET }}" -e TEST_PHONE_NUMBER="${{ secrets.TEST_PHONE_NUMBER }}" -e WHATSAPP_PHONE_ID="${{ secrets.WHATSAPP_PHONE_ID }}" -e WHATSAPP_TOKEN="${{ secrets.WHATSAPP_TOKEN }}" -e WHATSAPP_VERIFY_TOKEN="${{ secrets.WHATSAPP_VERIFY_TOKEN }}" --name smartmoveback-container mattdv57/smartmoveback
