name: Docker Image CD

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull mattdv57/smartmoveback:latest
    - name: Delete Old docker container
      run: sudo docker rm -f smartmoveback-container || true
    - name: Run Docker container
      env:
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: sudo docker run -d -p 8080:8080 --name smartmoveback-container mattdv57/smartmoveback
     
