name: Docker Image CD

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Delete Old docker container
      run: sudo docker rm -f smartmoveback-container || true
    - name: Pull Docker image
      run: sudo docker pull mattdv57/smartmoveback:latest
    - name: Login Dockerhub
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}} 
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Create .env file
      run: |
          echo "DATABASE_URL=${{ secrets.MONGO_CONNECTION_STRING }}" >> .env
          echo "AMBIENTE= ${{ secrets.Ambiente }}" >> .env

    - name: Run Docker container
      run: sudo docker run -d -p 3000:3000 --name smartmoveback-container --env-file .env mattdv57/smartmoveback
