name: Docker Image CI

run-name: ${{ github.actor }} is testing Docker Image CI with GitHub Actions 🚀
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
          distribution: 'temurin'
          java-version: '17'
    - name: Build Project
      run: mvn install -DskipTests -f admininterna/pom.xml
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login Dockerhub
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build and push

    - name: Build and push
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 3
        command: |
          docker build \
          -t mattdv57/smartmoveback:latest \
          --build-arg AMBIENTE ='${{ secrets.Ambiente }}'  .
          push: true
      
