name: Docker Image CI

run-name: ${{ github.actor }} is testing Docker Image CI with GitHub Actions 🚀
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
          distribution: 'temurin'
          java-version: '17'
    - name: Build Project
      run: mvn install -DskipTests -f admininterna/pom.xml
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login Dockerhub
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build and push
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 3
        command: |
            docker build \
            -t mattdv57/smartmoveback \
            --build-arg ACCESS_TOKEN_SECRET='${{ secrets.ACCESS_TOKEN_SECRET }}' \
            --build-arg DOCKER_PASSWORD='${{ secrets.DOCKER_PASSWORD }}' \
            --build-arg DOCKER_USER='${{ secrets.DOCKER_USER }}' \
            --build-arg LDAP_ADMIN_DN='${{ secrets.LDAP_ADMIN_DN }}' \
            --build-arg LDAP_ADMIN_PASSWORD='${{ secrets.LDAP_ADMIN_PASSWORD }}' \
            --build-arg LDAP_URL='${{ secrets.LDAP_URL }}' \
            --build-arg MONGO_CONNECTION_STRING2='${{ secrets.MONGO_CONNECTION_STRING2 }}' \
            --build-arg DATABASE_URL='${{ secrets.DATABASE_URL }}' \
            --build-arg PORT='${{ secrets.PORT }}' \
            --build-arg REFRES_TOKEN_SECRET='${{ secrets.REFRES_TOKEN_SECRET }}' \
            --build-arg TEST_PHONE_NUMBER='${{ secrets.TEST_PHONE_NUMBER }}' \
            --build-arg WHATSAPP_PHONE_ID='${{ secrets.WHATSAPP_PHONE_ID }}' \
            --build-arg WHATSAPP_TOKEN='${{ secrets.WHATSAPP_TOKEN }}' \
            --build-arg TEST_PHONE_NUMBER='${{ secrets.TEST_PHONE_NUMBER }}' \
            --build-arg LDAP_URL_SECURE='${{ secrets.LDAP_URL_SECURE }}' \
            --build-arg LDAP_DN='${{ secrets.LDAP_DN }}' \
            --build-arg AWS_ACCESS_KEY_ID='${{ secrets.AWS_ACCESS_KEY_ID }}' \
            --build-arg AWS_SECRET_ACCESS_KEY='${{ secrets.AWS_SECRET_ACCESS_KEY }}' \
            --build-arg EVENT_BUS_ARN='${{ secrets.EVENT_BUS_ARN }}' \
            --build-arg SQS_URL='${{ secrets.SQS_URL }}' \
            --build-arg SQS_ARN='${{ secrets.SQS_ARN }}' \
            --build-arg WHATSAPP_VERIFY_TOKEN='${{ secrets.WHATSAPP_VERIFY_TOKEN }}' .

            docker tag smartmoveback mattdv57/smartmoveback:latest

            docker push mattdv57/smartmoveback:latest
      
